name: Convert

on:
  push:
    branches:
      - main
  workflow_call: # to make the workflow triggerable from other workflows (release.yaml)

jobs:
  converter:
    name: Converter
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Ensure src directory exists
        run: mkdir -p ./src

      - name: Convert JSON to YAML
        uses: fabasoad/data-format-converter-action@v0
        id: json2yaml
        with:
          input: "./src/ValentinGuigon_CV.json"
          from: "json"
          to: "yaml"

      - name: Save YAML to File
        run: echo "${{ steps.json2yaml.outputs.output }}" > ./src/ValentinGuigon_CV.yaml

      - name: Verify YAML file
        run: ls -l ./src/ValentinGuigon_CV.yaml # Check if the ValentinGuigon_CV.yaml file exists and its details

      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "github-actions"
          git add ./src/ValentinGuigon_CV.yaml
          git commit -m "Convert JSON to YAML and add ValentinGuigon_CV.yaml"
          git push origin main
