name: Convert

on:
  push:
    branches:
      - main

jobs:
  converter:
    name: Run converter
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Ensure src directory exists
        run: mkdir -p ./src

      - name: Convert JSON to YAML
        id: yaml2json
        uses: fabasoad/data-format-converter-action@main
        with:
          input: "./src/ValentinGuigon_CV.json"
          from: "json"
          to: "yaml"

      - name: Save YAML to File
        run: echo "${{ steps.yaml2json.outputs.output }}" > ./src/ValentinGuigon_CV.yaml

      - name: Verify YAML file
        run: ls -l ./src/ValentinGuigon_CV.yaml # Check if the ValentinGuigon_CV.yaml file exists and its details
