name: Release a CV

on:
  push:
    branches:
      - main # Replace with your main branch name or use '*' for all branches

permissions:
  contents: write

jobs:
  convert_json_to_yaml:
    name: Converter
    uses: ./.github/workflows/convert.yaml
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
