name: Release a CV

on:
  push:
    tags:
      - "*" # Any tag pushed to the repository

permissions:
  contents: write

jobs:
  convert_json_to_yaml:
    name: Convert JSON to YAML
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Call Convert Workflow
        uses: ./.github/workflows/convert.yaml

  render_cv:
    name: RenderCV
    needs: convert_json_to_yaml
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Call RenderCV Workflow
        uses: ./.github/workflows/rendercv.yaml

  build:
    needs: render_cv
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Download RenderCV Output
        uses: actions/download-artifact@v4
        with:
          name: RenderCV Output
          path: rendercv_output
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            rendercv_output/*_CV.pdf
            rendercv_output/*_CV.tex
          generate_release_notes: true
          make_latest: true
