name: Release a CV

on:
  push:
    branches:
      - main # Replace with your main branch name or use '*' for all branches

permissions:
  contents: write

jobs:
  convert_json_to_yaml:
    runs-on: ubuntu-latest
    steps:
      - uses: fabasoad/data-format-converter-action@v0
        id: json2yaml
        with:
          input: "ValentinGuigon_CV.json"
          from: "json"
          to: "yaml"
      - name: Print result
        run: echo "${{ steps.json2yaml.outputs.output }}"
