name: Release a CV

on:
  push:
    branches:
      - main # Replace with your main branch name or use '*' for all branches

jobs:
  convert_and_render:
    name: Convert and Render CV
    runs-on: ubuntu-latest
    needs: convert
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

  convert:
    name: Convert CV JSON to YAML
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Convert Workflow
        uses: ./.github/workflows/convert.yaml

  render:
    name: Render CV PDF
    runs-on: ubuntu-latest
    needs: convert
    steps:
      - name: Trigger RenderCV Workflow
        uses: ./.github/workflows/rendercv.yaml
