name: Release a CV

on:
  push:
    tags:
      - main # Replace with your main branch name or use '*' for all branches

permissions:
  contents: write

jobs:
  test_workflow:
    runs-on: ubuntu-latest
    steps:
      - uses: fabasoad/data-format-converter-action@v0
        id: yaml2json
        with:
          input: "docker-compose.yml"
          from: "yaml"
          to: "json"
      - name: Print result
        run: echo "${{ steps.yaml2json.outputs.output }}"
