name: Release a CV

on:
  push:
    branches:
      - main # Replace with your main branch name or use '*' for all branches

permissions:
  contents: write

jobs:
  converter:
    name: Converter
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Ensure src directory exists
        run: mkdir -p ./src

      - name: Convert JSON to YAML
        uses: fabasoad/data-format-converter-action@v0
        id: json2yaml
        with:
          input: "./src/ValentinGuigon_CV.json"
          from: "json"
          to: "yaml"

      - name: Save YAML to File
        run: echo "${{ steps.json2yaml.outputs.output }}"
