name: Release a CV

on:
  push:
    branches:
      - main # Replace with your main branch name or use '*' for all branches

jobs:
  convert_json_to_yaml:
    uses: ./.github/workflows/convert.yaml
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}

  call_rendercv_workflow:
    name: RenderCV
    needs: convert_json_to_yaml
    uses: ./.github/workflows/rendercv.yaml
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
